### ISSUE TITLE
Let Companies send messages to Fellows as part of their pitch request

### ISSUE THREAD

**Issue by jtarre** [mikepatt77/vfa-placement-portal#88]
This is a long shot, but this would be the biggest win if for some reason it wasn't too difficult an implementation. Companies have started going outside the portal to individually email Fellows about job opps. 

We would love to bring this behavior into the portal. Is this something achievable over the course of a few weeks as part of maintenance? Totally fine if it's not, just wanted to throw it out there. 
![screen shot 2014-04-10 at 6 45 41 pm](https://cloud.githubusercontent.com/assets/1143894/2674453/dc8f2332-c101-11e3-862b-6632e980557e.png)

**Comment by mikepatt77** [comment]
Done with PR: https://github.com/mikepatt77/vfa-placement-portal/pull/165
